-- d053_tape_and_batch_files.sql
-- DB-backed file attachments for tapes and electrode cut batches, mirroring
-- the proven electrolyte_files / separator_files pattern (bytea in DB,
-- authenticated list/upload/download/delete routes).
--
-- WHY: the lab attaches working documents to physical items ? ???? ???????,
-- Excel sheets, scans. Batteries (electrochem), materials, electrolytes and
-- separators already support this; tapes and cut batches were the gap.
--
-- Forward-only, additive, idempotent.

BEGIN;

CREATE TABLE IF NOT EXISTS tape_files (
  tape_file_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tape_id      integer NOT NULL REFERENCES tapes(tape_id) ON DELETE CASCADE,
  file_name    text NOT NULL,
  mime_type    text,
  file_data    bytea NOT NULL,
  uploaded_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tape_files_tape_id ON tape_files(tape_id);

CREATE TABLE IF NOT EXISTS electrode_cut_batch_files (
  cut_batch_file_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cut_batch_id      integer NOT NULL REFERENCES electrode_cut_batches(cut_batch_id) ON DELETE CASCADE,
  file_name         text NOT NULL,
  mime_type         text,
  file_data         bytea NOT NULL,
  uploaded_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ecb_files_cut_batch_id ON electrode_cut_batch_files(cut_batch_id);

DO $$
BEGIN
  IF to_regclass('public.schema_migrations') IS NOT NULL THEN
    INSERT INTO schema_migrations (migration_name, migration_stream, source, notes)
    VALUES ('d053_tape_and_batch_files.sql', 'dalia', 'migration_file',
            'File attachments (bytea) for tapes and electrode cut batches, electrolyte_files pattern.')
    ON CONFLICT (migration_name) DO NOTHING;
  END IF;
END $$;

COMMIT;
